README.md, index.js, package.json, test/index.test.js
I'd like to implement the ability to use multiple scms feature (https://github.com/screwdriver-cd/screwdriver/issues/365).
The other related modules are also being modified.
This PR adds `_getScmContexts` and `_canHandleWebhook` functions for the multiple scms feature.
issue: https://github.com/screwdriver-cd/screwdriver/issues/365
Before merging for test success: https://github.com/screwdriver-cd/scm-base/pull/43
related changes:
- https://github.com/screwdriver-cd/data-schema/pull/152
- https://github.com/screwdriver-cd/data-schema/pull/155
- https://github.com/screwdriver-cd/screwdriver/pull/632
- https://github.com/screwdriver-cd/models/pull/180
- https://github.com/screwdriver-cd/scm-router/pull/1
- https://github.com/screwdriver-cd/scm-base/pull/43
- …
=> feat(365)-7: Add getScmContexts and canHandleWebhook functions

index.js, package.json, screwdriver.yaml, test/index.test.js
We've recently added a [subdirectory support](https://github.com/screwdriver-cd/screwdriver/issues/911) to Screwdriver.
This PR pulls in the latest scm-base and also:
- fixes spacing
- uses semantic release template
- adds getChangedFiles method
Blocked by https://github.com/screwdriver-cd/data-schema/pull/220
Blocked by https://github.com/bdangit/scm-gitlab/pull/11
Related to https://github.com/screwdriver-cd/screwdriver/issues/911
Resolves https://github.com/bdangit/scm-gitlab/issues/13
=> feat(911): Pull in latest scm-base. BREAKING CHANGE: new scm-base

index.js, test/data/gitlab.push.json, test/index.test.js
I'd like to implement the skipping builds feature (screwdriver-cd/screwdriver#587)
I've already changed `scm-github` and `scm-bitbucket` module to do it (screwdriver-cd/scm-github#64 , screwdriver-cd/scm-bitbucket#40)
This PR adds lastCommitMessage to the result of `parseHook`.
- issue: screwdriver-cd/screwdriver#587
- webhook spec: https://docs.gitlab.com/ce/user/project/integrations/webhooks.html
=> feat(587): Add lastCommitMessage to parsed hook

index.js, package.json, test/index.test.js
Since we are removing setting default branch in API/UI, we will need to set it in the plugin.
This PR sets the default branch to `default_branch` if not provided.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2185
=> fix(2185): Use default_branch [1.5]

index.js, package.json, screwdriver.yaml
Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/joi version and fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958
=> feat: upgrade hapiv19 dependencies. BREAKING CHANGE: new major data-schema version

index.js, package.json, test/index.test.js
Gitlab requires the path to a file be URI encoded.
This PR URI encodes the rootDir path.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2398
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.
=> fix(2398): URI encode path to file for getFile

index.js
Getting errors with:
```
/bin/sh: 2: /tmp/step.sh: Syntax error: "&&" unexpected
```
This PR removes extra semicolon from readOnly command.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437, https://github.com/screwdriver-cd/scm-gitlab/pull/41
=> fix(2437): Remove extra semicolon in get checkout command [2]

index.js, test/index.test.js
Add Gitlab PR Status Mapping for PENDING status.
SCM status checks should support PENDING status.
https://docs.screwdriver.cd/user-guide/metadata#additional-pull-request-checks need to support PENDING status
Jira:
screwdriver-cd/screwdriver#2449
More related PRs:
screwdriver-cd/scm-github#189
screwdriver-cd/models#496
https://github.com/screwdriver-cd/models/pull/506
https://github.com/screwdriver-cd/scm-github/pull/190
https://github.com/screwdriver-cd/scm-gitlab/pull/43
https://github.com/screwdriver-cd/data-schema/pull/450
=> feat: Add state map changes for pending

package.json
Semantic release package has been updated lately and changes need to be made in package.json.
This PR updates package.json with proper git url, release.
See https://github.com/screwdriver-cd/data-schema/blob/master/package.json for reference
=> fix: semantic release in package.json

index.js
A GitLab project can also have [ownership granted at the encompassing Group level](https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions).
This enables group owners to also create pipelines for projects they have admin access to.
* https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions
=> feat(auth): Check a user's Group-level permissions when checking for Admin access

index.js, test/index.test.js
Port the throwError function from scm-github so that the error handling of parseUrl can be done normally.
https://github.com/screwdriver-cd/scm-github/blob/e554b40619b8530d0eadc9ac02f35e3826900ff0/index.js#L57
Error handling of parseUrl is successful
https://github.com/screwdriver-cd/screwdriver/pull/2674
=> fix: Porting throwError function for proper error handling of parseUrl

index.js, package.json, test/index.test.js
In order to support getting provider config dynamically in screwdriver.yaml, we need to be able to pass in the full path to getFile instead of the scmUri, etc.
This PR changes getFile method to allow using full path to get repo owner, name, branch, etc info.
https://github.com/screwdriver-cd/screwdriver/issues/2676
Related to https://github.com/screwdriver-cd/scm-github/pull/204
=> fix(2676): Add option to pass in checkoutUrl as path to getFile

index.js, package.json, test/data/gitlab.merge_request.comments.json, test/index.test.js
If multiple jobs have PR comments, the later job's comment overwrites the earlier job's comment.
We change so that PR comments are only edited by the same job in the same pipeline.
https://docs.gitlab.com/ee/api/notes.html
https://github.com/screwdriver-cd/screwdriver/issues/2695
Reflect the following PRs before reflecting this.
- https://github.com/screwdriver-cd/data-schema/pull/489
- https://github.com/screwdriver-cd/models/pull/543
=> feat(2695): Does not overwrite PR comment that from other PR job

index.js, package.json, test/data/gitlab.merge_request.comments.json, test/index.test.js
allow user to split pr comment into different ones
https://github.com/screwdriver-cd/screwdriver/issues/2873
=> feat(2873): allow user to split pr comments

index.js, test/index.test.js
The following PR needs to get a SCM user id.
https://github.com/screwdriver-cd/screwdriver/pull/2890
This PR will include a GitLab id in the return value of `decorateAuthor`.
This PR will add a GitLab id in the return value of `decorateAuthor`.
I cannot actually test this by GitLab API, so try this please.
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/2892
=> feat(2892): get GitLab user ID

index.js, test/index.test.js
Follow up of PR https://github.com/screwdriver-cd/scm-gitlab/pull/57
This PR normalize the type of GitLab user id to String.
https://github.com/screwdriver-cd/screwdriver/issues/2892#issuecomment-1602452632
=> fix(2892): normalize the type of GitLab user id to String

package.json
BREAKING CHANGE: Move workflowGraph out of config and keep it at the same level as config
Move pipeline template workflowGraph out of config into a new field
Upgrading dependencies
https://github.com/screwdriver-cd/screwdriver/issues/3171
=> feat(feat(3171): Move pipeline template workflowGraph out of config into a new field

index.js, test/index.test.js
Currently, the `_parseHook` method  returns Object or null or throw Error.
However, their return values are not properly conditioned.
Organize the return values by the following:
- return Object (parsed result): the `scm` is correct and Screwdriver do actions with the webhook (e.g. `push` event)
- return null: the `scm` is correct and Screwdriver do nothing (e.g. `delete` event)
- throw Error: the `scm` is not correct
Then we can handle whether the webhook is correct or not at [here](https://github.com/screwdriver-cd/screwdriver/blob/ef31fca55eaff2548f7486795de41e84f87a675d/plugins/webhooks/index.js#L68-L73).
Issue
- https://github.com/screwdriver-cd/screwdriver/issues/3225
PR
- https://github.com/screwdriver-cd/scm-router/pull/37
I confirm that this contribution is made under the terms …
=> fix(3225): organize the return values of _parseHook [2]

package.json, test/index.test.js
Changes made in the https://github.com/screwdriver-cd/scm-base/pull/101 has resulted in few test failures
Adapt the tests to align with the latest changes
https://github.com/screwdriver-cd/screwdriver/issues/3384
=> fix(3384): Failure to get user info from scm should not throw error

index.js, test/index.test.js
When JSON.stringify() is applied to certain control characters, their character representation changes.
```
> JSON.stringify({x: '\u001F'})
'{"x":"\\u001f"}'
> JSON.stringify({x: '\x1F'})
'{"x":"\\u001f"}'
```
Therefore, if you use the value obtained by re-stringifying the payload after JSON.parse for verifying the signature, it will fail because the contents do not match.
- The original payload will be used for signature verification.
- Enable passing the string before parsing to the _parseHook in scm components.
- https://github.com/screwdriver-cd/scm-base/pull/102
- https://github.com/screwdriver-cd/scm-github/pull/250
- https://github.com/screwdriver-cd/scm-gitlab/pull/74
- https://github.com/screwdriver-cd/scm-bitbucket/pull/102
- https://github.com/screwdriver-cd/scm-router/pull/39 …
=> fix: Verify signature of payloads containing control characters [3]
